# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-10-05 19:16
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='age',
            field=models.IntegerField(blank=True, default=None, max_length=2, null=True),
        ),
    ]
