# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-10-26 16:09
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('board', '0002_partner_walletlger'),
    ]

    operations = [
        migrations.AlterField(
            model_name='walletlger',
            name='wallet',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='board.Wallet'),
        ),
    ]
