# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-10-26 16:09
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('board', '0003_auto_20171026_1609'),
    ]

    operations = [
        migrations.AlterField(
            model_name='walletlger',
            name='message',
            field=models.CharField(default=' ', max_length=200),
        ),
    ]
